# ============================================
# CHARACTER DATA (CharacterData.gd)
# ============================================
# PURPOSE: Resource class that defines a playable character
# TYPE: Resource (data container)
#
# DO NOT EDIT THIS FILE!
# To add/edit characters, use CharacterRegistry.gd instead
#
# This file defines what properties a character can have.
# CharacterRegistry.gd uses this template to create actual characters.
# ============================================

extends Resource
class_name CharacterData

# ==========================================
# BASIC INFO
# ==========================================
@export var character_id: String = ""  # Unique identifier (e.g., "hero", "warrior")
@export var character_name: String = ""  # Display name (e.g., "Hero", "Warrior")
@export var description: String = ""  # Short description shown in character select

@export var portrait: Texture2D  # Character portrait for selection screen (optional)
@export var sprite_texture: Texture2D  # Character sprite for in-game use (optional)

# ==========================================
# STARTING STATS
# ==========================================
# These determine the character's base stats at game start
@export_group("Starting Stats")

@export var starting_health: float = 100.0
# Base HP the character starts with
# Default: 100
# Lower = fragile (75), Higher = tank (150)

@export var starting_speed: float = 100.0
# Movement speed
# Default: 100
# Lower = slow (80), Higher = fast (130)

@export var starting_damage_multiplier: float = 1.0
# Multiplier applied to all weapon damage
# Default: 1.0 (normal damage)
# Examples: 0.8 = 20% less damage, 1.5 = 50% more damage

@export var starting_fire_rate_multiplier: float = 1.0
# Multiplier applied to weapon fire rate
# Default: 1.0 (normal fire rate)
# Examples: 0.9 = 10% slower, 1.3 = 30% faster

# ==========================================
# PASSIVE BONUSES
# ==========================================
# These are permanent bonuses the character has
# All default to 0 (no bonus)
@export_group("Passive Bonuses")

@export var bonus_crit_chance: float = 0.0
# Added to base critical hit chance
# Value range: 0.0 to 1.0 (0% to 100%)
# Examples: 0.0 = no bonus, 0.1 = +10% crit chance, 0.15 = +15%

@export var bonus_crit_damage: float = 0.0
# Added to critical damage multiplier
# Value range: 0.0 and up
# Examples: 0.0 = no bonus, 0.2 = +20% crit damage, 0.5 = +50%

@export var bonus_luck: float = 0.0
# Increases dodge chance and double drop chance
# Value range: 0.0 to 1.0
# Examples: 0.0 = no bonus, 0.05 = +5% luck, 0.1 = +10%

@export var bonus_xp_gain: float = 0.0
# Percentage bonus to XP gained from kills
# Value range: 0.0 and up
# Examples: 0.0 = no bonus, 0.1 = +10% XP, 0.25 = +25% XP

# ==========================================
# STARTING EQUIPMENT
# ==========================================
@export_group("Starting Equipment")

@export var starting_weapon: String = "Pistol"
# Name of weapon the character starts with
# Available weapons:
#   "Pistol" - Balanced starter weapon
#   "Shotgun" - Close range, high damage
#   "Assault Rifle" - Fast fire rate
#   "Sniper Rifle" - Long range, high damage
#   "Machine Gun" - Very fast fire rate
#   "Burst Rifle" - Fires in bursts

@export var starting_items: Array[Dictionary] = []
# Array of items the character starts with
# Format: [{"name": "ItemName", "quantity": amount}, ...]
# Examples:
#   [{"name": "Wood", "quantity": 10}]
#   [{"name": "Wolf Fur", "quantity": 5}, {"name": "Plant Fiber", "quantity": 5}]
# Available items: "Wood", "Wolf Fur", "Plant Fiber", "Mushroom"

# ==========================================
# VISUAL CUSTOMIZATION
# ==========================================
@export_group("Visual")

@export var primary_color: Color = Color.WHITE
# Primary color tint for character sprite (optional)
# Default: White (no tint)
# Examples: Color(1, 0, 0) = red, Color(0, 1, 0) = green, Color(0, 0, 1) = blue

@export var secondary_color: Color = Color.WHITE
# Secondary color tint for character (optional)
# Default: White (no tint)
# Used for accent colors on the character sprite


# ============================================
# NOTES FOR DEVELOPERS
# ============================================
#
# This is a RESOURCE class - it's a data template.
# Actual character instances are created in CharacterRegistry.gd
#
# To add a new stat/property:
# 1. Add it here as an @export variable
# 2. Update CharacterRegistry.gd to set it for each character
# 3. Update CharacterSelectUI.gd if you want it displayed
# 4. Update the player script to use the new stat
#
# ============================================
